// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uvarjavbbkijiwavycvy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV2YXJqYXZiYmtpaml3YXZ5Y3Z5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg4NDkzNTMsImV4cCI6MjA2NDQyNTM1M30.uPri4olcVUW5Tp6zbgz7u1DSZW-CfUDwE0Ph_S4PQMI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);